# Exercice d'entrainement aux librairie


## I - Numpy

Exercices : 

1. Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [21]:
from matplotlib import pyplot as plt 
import numpy as np

1. Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus). 

In [22]:
t = np.arange(1,11)

print(t)

[ 1  2  3  4  5  6  7  8  9 10]


2. Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1. 

In [23]:
t = np.random.rand(5)
print(t)

[0.74615463 0.1103356  0.05665125 0.74314002 0.04569974]


3. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments. 

In [34]:
def somme(tab) :
    somme = np.sum(x)
    return somme

x = np.random.randint(100,size=(10))

print(somme(x))

420


4. Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [32]:

def produit_scalaire(tab1, tab2) :
    scalaire = np.dot(a,b)
    return scalaire


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(produit_scalaire(a, b))

32


5. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [33]:
def element_unique(tab) : 
    element = np.unique(c)
    return element

c = np.array([4, 5, 6, 6, 3])
print(element_unique(c))


[3 4 5 6]


6. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [36]:
def ordre(tab) : 
    croissant = np.sort(tab)
    return croissant


d = np.random.randint(100,size=(10))

print(ordre(d))

[ 2 10 13 18 23 26 57 62 83 92]


7. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [37]:
def moyenne(tab) : 
    moy = np.mean(tab)
    return moy

e = np.random.randint(10,size=(10))
print(e)
print(moyenne(e))

[2 8 5 8 9 1 4 0 7 5]
4.9


8. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [55]:
def replace(tab) :
    return np.where(tab <= 5, 0,1)

f = np.random.randint(10,size=(10))    
print(f)
print(replace(tab))

[3 7 8 0 7 0 8 5 0 3]
[0 0 1 1 0 0 0 1 0 1]


9. Créez une fonction qui prend un tableau NumPy de nombres entiers en entrée et renvoie un nouveau tableau contenant uniquement les nombres premiers du tableau d'origine.

In [70]:
# 2️⃣ Fonction pour tester si un nombre est premier
def isPrime(n):
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True    

def est_premier(tab):
    premier = []
    for i in tab :
        if isPrime(i) :
            premier.append(int(i))
    return premier

f = np.random.randint(20,size=(10)) 
print(f)
print(est_premier(f))


[11 13 15  7  7 11 19  6 17  4]
[11, 13, 7, 7, 11, 19, 17]


# II - Pyplot