# Exercice d'entrainement aux librairie


## I - Numpy

Exercices : 

1. Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus).

In [2]:
from matplotlib import pyplot as plt 
import numpy as np

1. Créez un tableau NumPy contenant les entiers de 1 à 10 (inclus). 

In [ ]:
# Fonction de numpy

t = np.arange(1,11)
print(t)

#! A la main

nombre = 0
def liste() : 
    global nombre
    for i in range(1) : 
        nombre = nombre+1
    return nombre

print(nombre)

tab = []
for i in range(10) :
    tab.append(liste())
    
print(tab)

[ 1  2  3  4  5  6  7  8  9 10]
0
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2. Créez un tableau NumPy contenant 5 valeurs flottantes générées aléatoirement entre 0 et 1. 

In [14]:
t = np.random.rand(5)
print(t)

nombre = 1

def random() : 
    global nombre
    nombre = (nombre * 9 +1) % 10
    return nombre

print(nombre)

tab = []
for i in range(10) : 
    tab.append(random())
    
print(tab)

[0.05079396 0.02064949 0.9988779  0.51802791 0.13482049]
1
[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]


3. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la somme de ses éléments. 

In [ ]:
# Avec fonction de Numpy
def somme(tab) :
    somme = np.sum(x)
    return somme

x = np.random.randint(100,size=(10))

print(somme(x))

# A la main
def sommeBis(tab):
    _somme = 0
    longueur = len(tab)
    for i in range(longueur):
        _somme = _somme + tab[i]
    return _somme

print(sommeBis(x))

449
449


4. Créez une fonction qui prend deux tableaux NumPy en entrée et renvoie le produit scalaire de ces deux tableaux (dot product).

In [ ]:

#! Avec fonction native
def produit_scalaire(tab1, tab2) :
    scalaire = np.dot(a,b)
    return scalaire


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(produit_scalaire(a, b))

#! A la main

def scalaire(tab1, tab2):
    resultat = 0
    for i in range(len(tab1)):
        resultat += tab1[i] * tab2[i]  # produit élément par élément
    return resultat

w = np.array([1, 2, 3])
x = np.array([4, 5, 6])

print(scalaire(w,x))


32
32


5. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant uniquement les éléments uniques du tableau d'origine.

In [40]:
def element_unique(tab) : 
    element = np.unique(c)
    return element

c = np.array([4, 5, 6, 6, 3])
print(element_unique(c))

#! def ordre croissant
#? i > i (inverser) i <i laisser tel quel

#? if element not in tab



def unique_number(tab) :
    tab2 = []
    for i in tab :
        if i not in tab2 : 
            tab2.append(i)
    return np.asarray(tab2)

tab = [4, 5, 6, 6, 3,3, 4]

print(unique_number(c))
#! def i = i (append() prendre que le premier), i != i append()


[3 4 5 6]
[4 5 6 3]


6. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau contenant les éléments triés par ordre croissant.

In [ ]:
def ordre(tab) : 
    croissant = np.sort(tab)
    return croissant


d = np.random.randint(100,size=(10))

print(ordre(d))

# def ordreBy(tab) : 
#     temp = 0
#     tab2 = []
#     for i in tab : 
#         for j in range(len(liste)) : 
#             n = tab[j]
#             if i <= n :
#                 temp = a
#                 a= b
#                 b = temp
#             else :
#                 tab2.append(temp)
#     return(np.asarray(tab2))

tab = [3, 4, 6, 6, 3,3, 4]



def sorting(liste):
    for i in range(len(liste)):
        mini = i
        for j in range(i+1, len(liste)):
            if liste[j] < liste[mini]:
                mini = j
        temp = liste[i]
        liste[i] = liste[mini]
        liste[mini] = temp
    return liste

def ordre_croissant(tab):
    tab2 = []                # nouvelle liste triée
    while len(tab) > 0:      # tant qu'il reste des éléments
        mini = tab[0]        # on suppose que le premier est le plus petit
        for element in tab:  # on cherche le vrai minimum
            if element < mini:
                mini = element
        tab2.append(mini)    # on ajoute le minimum à la nouvelle liste
        tab.remove(mini)     # on l'enlève de l'ancienne liste
    return tab2

print(ordre_croissant(tab))

tab = [5, 4, 6, 6, 3, 3, 4]


[ 6 20 30 34 72 80 82 85 89 99]
[3, 3, 3, 4, 4, 6, 6]


7. Créez une fonction qui prend un tableau NumPy en entrée et renvoie la moyenne, la médiane et l'écart type de ses éléments.

In [ ]:
def moyenne(tab) : 
    moy = np.mean(tab)
    return moy

e = np.random.randint(10,size=(10))

print(e)
print(moyenne(e))

[2 8 5 8 9 1 4 0 7 5]
4.9


8. Créez une fonction qui prend un tableau NumPy en entrée et renvoie un nouveau tableau où tous les éléments inférieurs à 5 sont remplacés par 0 et tous les éléments supérieurs ou égaux à 5 sont remplacés par 1.

In [55]:
def replace(tab) :
    return np.where(tab <= 5, 0,1)

f = np.random.randint(10,size=(10))    
print(f)
print(replace(tab))

[3 7 8 0 7 0 8 5 0 3]
[0 0 1 1 0 0 0 1 0 1]


9. Créez une fonction qui prend un tableau NumPy de nombres entiers en entrée et renvoie un nouveau tableau contenant uniquement les nombres premiers du tableau d'origine.

In [70]:
# 2️⃣ Fonction pour tester si un nombre est premier
def isPrime(n):
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            return False
    return True    

def est_premier(tab):
    premier = []
    for i in tab :
        if isPrime(i) :
            premier.append(int(i))
    return premier

f = np.random.randint(20,size=(10)) 
print(f)
print(est_premier(f))


[11 13 15  7  7 11 19  6 17  4]
[11, 13, 7, 7, 11, 19, 17]


# II - Pyplot

Exercices : 

1. Tracer un graphe linéaire des points (x, y) où x = [0, 1, 2, 3, 4] et y = [1, 4, 3, 8, 5].